"""empty message

Revision ID: 146cc28d11b8
Revises: 836d067cf18a
Create Date: 2020-02-19 17:36:52.493865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146cc28d11b8'
down_revision = '836d067cf18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customeruser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dynamic_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('html', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('html'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('html', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('html'),
    sa.UniqueConstraint('name')
    )
    op.create_table('userprod',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('temp')
    op.drop_table('user')
    op.drop_table('dynmic__temp')
    op.drop_table('user_product_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_list',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"user_product_list_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], name='user_product_list_orderId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['customers.id'], name='user_product_list_userId_fkey'),
    sa.PrimaryKeyConstraint('Id', name='user_product_list_pkey')
    )
    op.create_table('dynmic__temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('html', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dynmic__temp_pkey'),
    sa.UniqueConstraint('html', name='dynmic__temp_html_key'),
    sa.UniqueConstraint('name', name='dynmic__temp_name_key')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('html', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='temp_pkey'),
    sa.UniqueConstraint('html', name='temp_html_key'),
    sa.UniqueConstraint('name', name='temp_name_key')
    )
    op.drop_table('userprod')
    op.drop_table('template')
    op.drop_table('dynamic_template')
    op.drop_table('customeruser')
    # ### end Alembic commands ###
