"""empty message

Revision ID: 20e7ce451427
Revises: 75aace516350
Create Date: 2020-02-18 22:48:52.494990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7ce451427'
down_revision = '75aace516350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=True),
    sa.Column('productName', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('productDescription', sa.String(length=1000), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('unitPrice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
