"""empty message

Revision ID: 4af0ff244835
Revises: 93a9b89cef7c
Create Date: 2020-02-18 22:55:22.172281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af0ff244835'
down_revision = '93a9b89cef7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('SKU', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'SKU')
    # ### end Alembic commands ###
