"""empty message

Revision ID: 4f543ebf633c
Revises: ed3f1b106de4
Create Date: 2020-02-19 16:18:43.431987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f543ebf633c'
down_revision = 'ed3f1b106de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_list',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"user_product_list_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orderId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], name='user_product_list_orderId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['customers.id'], name='user_product_list_userId_fkey'),
    sa.PrimaryKeyConstraint('Id', name='user_product_list_pkey')
    )
    # ### end Alembic commands ###
