"""empty message

Revision ID: 58a3986410ab
Revises: d6bac85cfdd1
Create Date: 2020-02-19 17:27:29.059479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a3986410ab'
down_revision = 'd6bac85cfdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'age')
    # ### end Alembic commands ###
