"""empty message

Revision ID: 75aace516350
Revises: 667065719143
Create Date: 2020-02-18 22:32:16.441668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75aace516350'
down_revision = '667065719143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_list',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_list')
    # ### end Alembic commands ###
