"""empty message

Revision ID: 836d067cf18a
Revises: 59562525c877
Create Date: 2020-02-19 17:34:19.832900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d067cf18a'
down_revision = '59562525c877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registrationDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'registrationDate')
    # ### end Alembic commands ###
