"""empty message

Revision ID: 93a9b89cef7c
Revises: 20e7ce451427
Create Date: 2020-02-18 22:55:09.575156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a9b89cef7c'
down_revision = '20e7ce451427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'SKU')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('SKU', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
