"""empty message

Revision ID: cfd56e34d7d7
Revises: a57c97de163c
Create Date: 2020-02-18 10:55:06.077625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd56e34d7d7'
down_revision = 'a57c97de163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'price')
    # ### end Alembic commands ###
