"""empty message

Revision ID: d2ca877c5098
Revises: 04e87c2fc94e
Create Date: 2020-02-18 22:08:12.750836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ca877c5098'
down_revision = '04e87c2fc94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userProductid', sa.Integer(), nullable=True),
    sa.Column('productRating', sa.Integer(), nullable=True),
    sa.Column('reviewTitle', sa.String(length=100), nullable=True),
    sa.Column('reviewDetails', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
