"""empty message

Revision ID: e261626b88b9
Revises: cca4e121fea4
Create Date: 2020-02-19 17:48:02.634740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e261626b88b9'
down_revision = 'cca4e121fea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registrationDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'registrationDate')
    # ### end Alembic commands ###
