"""empty message

Revision ID: ed3f1b106de4
Revises: ef9fabdbaacd
Create Date: 2020-02-19 16:08:53.906119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3f1b106de4'
down_revision = 'ef9fabdbaacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_product_list', sa.Column('orderId', sa.Integer(), nullable=True))
    op.add_column('user_product_list', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_product_list', 'customers', ['userId'], ['id'])
    op.create_foreign_key(None, 'user_product_list', 'order', ['orderId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_product_list', type_='foreignkey')
    op.drop_constraint(None, 'user_product_list', type_='foreignkey')
    op.drop_column('user_product_list', 'userId')
    op.drop_column('user_product_list', 'orderId')
    # ### end Alembic commands ###
