"""empty message

Revision ID: ef9fabdbaacd
Revises: fea11b211147
Create Date: 2020-02-19 16:08:29.354868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9fabdbaacd'
down_revision = 'fea11b211147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_list_userId_fkey', 'user_product_list', type_='foreignkey')
    op.drop_constraint('user_product_list_orderId_fkey', 'user_product_list', type_='foreignkey')
    op.drop_column('user_product_list', 'userId')
    op.drop_column('user_product_list', 'orderId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_product_list', sa.Column('orderId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_product_list', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_product_list_orderId_fkey', 'user_product_list', 'order', ['orderId'], ['id'])
    op.create_foreign_key('user_product_list_userId_fkey', 'user_product_list', 'customers', ['userId'], ['id'])
    # ### end Alembic commands ###
